# 11.15.1 pthread cancel 陷阱
***

&emsp;&emsp;
最近几天看 core java，对于多线程部分提到了最好不要 stop、suspend、resume 线程。
在外部去干扰线程执行容易造成线程资源占用以及运行状态不合理。

&emsp;&emsp;
下面代码就是最近遇到一个问题的例子。
main -> func1 -> func2。
然后 main 等待 func1 建立完成之后 cancel 并且 join func1，而 func1 就是 join func2。
而 func2 里尝试持有一个 mutex lock，其中 mutex lock 里存在字段 holder\_ 表示哪个线程持有这个 lock。
为了确保 mutex lock 的锁释放正确，会在析构去 assert 没有任何线程持有这个 lock。
单独看这个 mutex lock 实现没有任何问题，但是在这个 cancel 线程场景下：

    #include <unistd.h>
    #include <linux/unistd.h>
    #include <pthread.h>
    #include <cassert>
    #include <cstdio>
    
    class Lock {
     public:
      Lock():holder_(0) {
        pthread_mutex_init(&lock_, NULL);
      }
      
      ~Lock(){
        assert(holder_ == 0);
        pthread_mutex_destroy(&lock_);
      }
      
      void lock() {
        pthread_mutex_lock(&lock_);
        holder_ = syscall(__NR_gettid);
      }
      
      void unlock() {
        holder_ = 0;
        pthread_mutex_unlock(&lock_);
      }
      
     private:
      pthread_mutex_t lock_;
      pid_t holder_;
    }; // class Lock
    
    static Lock lock;
    
    void* func2(void* arg) {
      printf("enter func2\n");
      lock.lock();
      
      while(1) {
        sleep(2);
      }
      
      lock.unlock();
      printf("exit func2\n");
      return NULL;
    }
    
    void* func1(void* arg) {
      printf("enter func1\n");
      pthread_t tid;
      pthread_create(&tid, NULL, func2, NULL);
      pthread_join(tid, NULL);
      printf("exit func1\n");
      return NULL;
    }
    
    int main() {
      pthread_t tid;
      pthread_create(&tid, NULL, func1, NULL);
      // wait thread func1 and func2 ready.
      sleep(1);
      pthread_cancel(tid);
      pthread_join(tid, NULL);
      printf("exit main\n");
      return 0;
    }

&emsp;&emsp;
运行结果：

    [zhangyan04@tc-hpc-dev.tc.baidu.com]$ ./a.out
    enter func1
    enter func2
    exit main
    a.out: main.cc:17: Lock::~Lock(): Assertion `holder_ == 0′ failed.
    已放弃 (core dumped)

&emsp;&emsp;
可以看到 func1 以及 func2 都没有正常退出，但是 main 函数是正常退出。
main 函数正常退出就会尝试析构全局这个 lock 对象，而这个 lock 对象在 func2 被持有。
这就是外部干扰线程的结果。

&emsp;&emsp;
对于这个问题解决办法非常简单，就是外部设置退出标记，线程去检测这个退出标记的置位，然后让这个线程自己决定如何退出。
所以对于线程控制更应该使用一种 cooperative 而不是 preemptive 的方式来达到。